server:
  port: 8082

dubbo:
  application:
    name: api-gateway-test
    version: 1.0.0
  registry:
    #address: N/A 泛化调用不能使用此方式
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: cn.bugstack.gateway.rpc
  config-center:
    timeout: 25000

api-gateway-sdk:
  address: http://127.0.0.1:8001  # 注册中心；从这里获取接口信息以及完成注册网关操作
  systemId: api-gateway-test-provider
  systemName: 网关sdk测试工程
  systemRegistry:  zookeeper://192.168.120.1:2181